### ISSUE TITLE
Release versions

### ISSUE THREAD

**Issue by Shredder121** [webjars/octicons#2]
Hello, is there a possibility that the new versions of octicons can be included in webjars?

**Comment by jamesward** [comment]
Let me know what version(s) you need.

**Comment by Shredder121** [comment]
According to [the release page](https://github.com/github/octicons/releases/) there have been some new releases.
I personally would like [v3.3.0](https://github.com/github/octicons/releases/tag/v3.3.0) to be present.

I don't know if it's easy to add the intermediate versions as well, for people migrating to webjars?

**Comment by Shredder121** [comment]
Awesome! Thanks! :+1:
